MODEL_FEATURES = {
    "load": [
        "hour",
        "minute",
        "dayofweek",
        "month",
        "is_nonworking_day",
        "load_lag_1",
        "load_lag_4",
        "load_lag_96",
        "load_lag_672",
    ],
    "wind": [
        "hour",
        "minute",
        "dayofweek",
        "month",
        "wind_lag_96",
        "wind_lag_672",
    ],
    "solar": [
        "hour",
        "minute",
        "dayofweek",
        "month",
        "sun_elevation",
        "solar_lag_96",
        "solar_lag_672",
    ],
    "price": [
        "load",
        "wind",
        "solar",
        "hour",
        "minute",
        "dayofweek",
        "month",
        "is_nonworking_day",
        "sun_elevation",
        "price_lag_1",
        "price_lag_2",
        "price_lag_4",
        "price_lag_8",
        "price_lag_24",
        "price_lag_48",
        "price_lag_96",
        "price_lag_192",
        "price_lag_672",
    ],
}

LAGS = {
        "load": [1, 4, 96, 672],
        "wind": [1, 96, 672],
        "solar": [96, 672],
        "price": [1, 2, 4, 8, 24, 48, 96, 192, 672],
    }